INSERT INTO paste_language (name, slug) VALUES ('Bash (shell)', 'bash');
INSERT INTO paste_language (name, slug) VALUES ('C#','csharp');
INSERT INTO paste_language (name, slug) VALUES ('C','c');
INSERT INTO paste_language (name, slug) VALUES ('C++','cpp');
INSERT INTO paste_language (name, slug) VALUES ('CSS','css');
INSERT INTO paste_language (name, slug) VALUES ('Diff','diff');
INSERT INTO paste_language (name, slug) VALUES ('Go','go');
INSERT INTO paste_language (name, slug) VALUES ('HTML','html');
INSERT INTO paste_language (name, slug) VALUES ('Java','java');
INSERT INTO paste_language (name, slug) VALUES ('Javascript','javascript');
INSERT INTO paste_language (name, slug) VALUES ('Perl','perl');
INSERT INTO paste_language (name, slug) VALUES ('PHP','php');
INSERT INTO paste_language (name, slug) VALUES ('Plain text','text');
INSERT INTO paste_language (name, slug) VALUES ('Python','python');
INSERT INTO paste_language (name, slug) VALUES ('Ruby','ruby');
INSERT INTO paste_language (name, slug) VALUES ('SQL','sql');
INSERT INTO paste_language (name, slug) VALUES ('XML','xml');
INSERT INTO paste_language (name, slug) VALUES ('YAML','yaml');
