insert into paste_language('name', 'key') values('Bash (shell)', 'bash');
insert into paste_language('name', 'key') values('C#','csharp');
insert into paste_language('name', 'key') values('C','c');
insert into paste_language('name', 'key') values('C++','cpp');
insert into paste_language('name', 'key') values('CSS','css');
insert into paste_language('name', 'key') values('Diff','diff');
insert into paste_language('name', 'key') values('Go','go');
insert into paste_language('name', 'key') values('HTML','html');
insert into paste_language('name', 'key') values('Java','java');
insert into paste_language('name', 'key') values('Javascript','javascript');
insert into paste_language('name', 'key') values('Perl','perl');
insert into paste_language('name', 'key') values('PHP','php');
insert into paste_language('name', 'key') values('Plain text','text');
insert into paste_language('name', 'key') values('Python','python');
insert into paste_language('name', 'key') values('Ruby','ruby');
insert into paste_language('name', 'key') values('SQL','sql');
insert into paste_language('name', 'key') values('XML','xml');
insert into paste_language('name', 'key') values('YAML','yaml');
