# Generated by Django 5.2.8 on 2025-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0002_auto_20180513_1644"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="paste",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
